/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school.proj;

/**
 *
 * @author UC 313
 */
public class adminwrk extends javax.swing.JFrame {

    /**
     * Creates new form adminwrk
     */
    public adminwrk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        studentmodules = new javax.swing.JButton();
        teachermodules = new javax.swing.JButton();
        studentreportcards = new javax.swing.JButton();
        feesubmissionmodules = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("Logout");

        jLabel1.setText("Menu Page");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        logout.setText("log out");
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Menu Page As Admin");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 260, -1));

        studentmodules.setBackground(new java.awt.Color(204, 204, 255));
        studentmodules.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentmodules.setText("Student Modules");
        studentmodules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentmodulesActionPerformed(evt);
            }
        });
        jPanel1.add(studentmodules, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 200, 30));

        teachermodules.setBackground(new java.awt.Color(204, 204, 255));
        teachermodules.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        teachermodules.setText("Teacher Modules");
        jPanel1.add(teachermodules, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 190, 30));

        studentreportcards.setBackground(new java.awt.Color(204, 204, 255));
        studentreportcards.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentreportcards.setText("Student Reports Cards");
        jPanel1.add(studentreportcards, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 230, 30));

        feesubmissionmodules.setBackground(new java.awt.Color(204, 204, 255));
        feesubmissionmodules.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        feesubmissionmodules.setText("Fee Submission Modules");
        feesubmissionmodules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesubmissionmodulesActionPerformed(evt);
            }
        });
        jPanel1.add(feesubmissionmodules, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\UC 313\\Downloads\\2 buliding.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feesubmissionmodulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesubmissionmodulesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feesubmissionmodulesActionPerformed

    private void studentmodulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentmodulesActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_studentmodulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminwrk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminwrk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminwrk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminwrk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminwrk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton feesubmissionmodules;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton studentmodules;
    private javax.swing.JButton studentreportcards;
    private javax.swing.JButton teachermodules;
    // End of variables declaration//GEN-END:variables
}
